### ISSUE TITLE
Omanyte/Omastar Themes and PokeCursors mismatched

### ISSUE THREAD

**Issue by SteadyMitch** [klauscfhq/hyper-pokemon#15]
## Description

When selecting the Omanyte or Omastar themes, I see that the themes are mismatched so that selecting Omanyte in the configuration gives the Omastar theme in Hyper.  Selecting Omastar in the configuration presents the Omanyte theme in Hyper.  However the PokeCursor seems to match correctly with the selected theme in the hyper config

Screenshot 1 - Omastar, but Omanyte theme
![image](https://user-images.githubusercontent.com/3466889/28476771-3ae1b7a6-6e1f-11e7-9392-756188029a3f.png)

Screenshot 2 - Omanyte, but Omastar theme
![image](https://user-images.githubusercontent.com/3466889/28476719-080585f6-6e1f-11e7-9c43-553753d957d9.png)

### Theme settings
Settings for screenshot

    // Hyper-Pokemon configs - Screenshot 1
    pokemon: 'omastar', // Define your favorite pokemon theme! 
    pokecursor: 'true', // Activate your theme's pokecursor! 
    pokemonSyntax: 'light', // Define the color of the terminal tabs! 
    unibody: 'true', // Define the color of the Hyper window header! 

    // Hyper-Pokemon configs - Screenshot 2
    pokemon: 'omanyte', // Define your favorite pokemon theme! 
    pokecursor: 'true', // Activate your theme's pokecursor! 
    pokemonSyntax: 'light', // Define the color of the terminal tabs! 
    unibody: 'true', // Define the color of the Hyper window header! 

## Environment

OS: Windows 10
Hyper: 1.3.3
Hyper Pokemon: 0.3.1

**Comment by tibuurcio** [comment]
Thanks for taking the time to report the issue! 😄

I've created a PR to fix it here #16 

If you want to get the right themes before a release goes out, go to `$homeDir/.hyper_plugins/hyper-pokemon/backgrounds` and swap the names for the Omanyte/Omastar background files and you're good to go!

**Comment by SteadyMitch** [comment]
Thank you @tibuurcio, that switched the themes for me.  After switching, I found that I had to switch the unibody color in pokemon.yml also.  Everything looks great, thank you for the quick response!

**Comment by klaudiosinani** [comment]
Hello @SteadyMitch! Thank you for reporting it! Feel free to share anything new you might come across! 😄 
@tibuurcio Awesome work! 🎉 😄

**Comment by SteadyMitch** [comment]
Will do, thanks again for the great work!  Definitely my favorite Hyper Theme by far 🥇

**Comment by klaudiosinani** [comment]
@SteadyMitch Haha thank you so much! Super happy that you enjoy it 😄
