### ISSUE TITLE
Hyper Migrating to xterm.js

### ISSUE THREAD

**Issue by DuIslingr** [klauscfhq/hyper-pokemon#2]
Dunno what I would label this as really but I thought I would inform you that Hyper seems to be planning to migrate to https://github.com/sourcelair/xterm.js/ . Dunno how that will affect this project but like I said thought it might be useful for you to know.
zeit/hyper#1275

**Comment by klaudiosinani** [comment]
Yep, I am aware, but a huge thank you for taking the time to drop by and post it : )
Just for the record it won't affect that much the internal hyper/electron API, so the whole ecosystem of hyper plugins & themes should be ok! 😄
