### ISSUE TITLE
Hyper-Pokemon Broken on 1.4.2?

### ISSUE THREAD

**Issue by DuIslingr** [klauscfhq/hyper-pokemon#22]
Hyper doesn't seem to want to load with hyper-pokemon enabled on 1.4.2

No error, the window just doesn't load, but I do see 2 of the processes in task manager going.

Idk if my windows build has anything to do with it but its 16257.

**Comment by klaudiosinani** [comment]
Indeed there was a minor regression introduced with the release of Hyper `1.4.0` but it was swiftly fixed thereafter with the release of [`1.4.2`](https://github.com/zeit/hyper/releases/tag/1.4.2) [`(#2139)`](https://github.com/zeit/hyper/pull/2139). 

On my end both `Hyper` & `hyper-pokemon` run smoothly; `win32 release 10.0.15063`

![untitled-1](https://user-images.githubusercontent.com/12670537/29927006-b5649cd2-8e6d-11e7-91bf-25647abc7ab5.png)

Have you tried maybe reinstalling `hyper-pokemon` or even clean install `Hyper` to its [latest version](https://github.com/zeit/hyper/releases/tag/1.4.2)?
Hopefully that will work out : ) 
Feel free reach back if the issue persist!

**Comment by DuIslingr** [comment]
My install was a clean install as i hadnt reinstalled hyper till yesterday. It says its 1.4.2 :/

**Comment by DuIslingr** [comment]
@klauscfhq 
with hyper-pokemon loaded
https://a.safe.moe/lmiUD.png
with it not loaded
https://a.safe.moe/bCiOG.png

**Comment by klaudiosinani** [comment]
Did you install `hyper-pokemon` through the `plugins` array inside of the `~/.hyper.js` file?
If not, you could definitely try doing it, there is a high chance that it might resolve the issue : )

**Comment by DuIslingr** [comment]
I tried both hpm-cli and just manually adding it. all hpm-cli does is add it to the hyper.js file, and hyper then downloads the files with npm or yarn. I tried dragging it to local plugin directory but its not loading from there at all even though its also specified to look there in hyper.js :/ I also note it also acquires some other things, which might be intentional, not entirely sure as i havent checked plugins before.

https://a.safe.moe/nZUwU.png
^^all this is installed upon adding hyper-pokemon to plugins.

**Comment by georgebax** [comment]
Try dragging the plugin folder into the node_modules folder too

**Comment by DuIslingr** [comment]
That's where it is....
https://a.safe.moe/OJHgG.png

**Comment by klaudiosinani** [comment]
Would you mind sharing your `~/.hyper.js` configuration, so we can have a better view on this?
It could be an other plugin not mixing that well with `hyper-pokemon`, thus preventing you from activating
 it 🤔

**Comment by DuIslingr** [comment]
Only other plugin i currently have is hypertheme. and the issue occurs even if i disable hypertheme.

```js
// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    // Choose either "stable" for receiving highly polished,
    // or "canary" for less polished but more frequent updates
    updateChannel: 'stable',

    // default font size in pixels for all tabs
    fontSize: 12,

    // font family with optional fallbacks
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.8)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BLOCK',

    // set to true for blinking cursor
    cursorBlink: false,

    // color of the text
    foregroundColor: '#fff',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',

    // custom css to embed in the terminal window
    termCSS: '',

    // set to `true` (without backticks) if you're using a Linux setup that doesn't show native menus
    // default: `false` on Linux, `true` on Windows (ignored on macOS)
    showHamburgerMenu: '',

    // set to `false` if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` on windows and Linux (ignored on macOS)
    showWindowControls: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    //
    // Windows
    // - Make sure to use a full path if the binary name doesn't work
    // - Remove `--login` in shellArgs
    //
    // Bash on Windows
    // - Example: `C:\\Windows\\System32\\bash.exe`
    //
    // Powershell on Windows
    // - Example: `C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe`
    shell: '',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],

    // for environment variables
    env: {},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: false

    // if true, on right click selected text will be copied or pasted if no
    // selection is present (true by default on Windows)
    // quickEdit: true

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: ["hypertheme", "hyper-pokemon"],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: [],

  keymaps: {
    // Example
    // 'window:devtools': 'cmd+alt+o',
  }
};
```

**Comment by klaudiosinani** [comment]
The theme does not use `default values` as setting options, so `user-defined` ones should be included. You can try adding the following `hyper-pokemon` settings, taken from the project's readme [`Usage`](https://github.com/champloohq/hyper-pokemon#usage) section, in order to activate the theme. I am confident that will resolve your issue : )

Here is a quick look;

```js
config: {
    //...
    colors: {
    //...
    },
    pokemon: 'gengar', // Define your favorite pokemon theme
    pokecursor: 'true', // Activate your theme's pokecursor
    pokemonSyntax: 'dark', // Define the color of the terminal tabs
    unibody: 'true', // Define the color of the Hyper window header
    poketab: 'false', // Deactivate your theme's poketab
    //...
}
```

**Comment by DuIslingr** [comment]
🤦‍♂️ ugh I cant believe I completely forgot that -_- is there no way for hpm-cli to automatically configure this though or something? Or maybe even via the terminal itself provided the terminal can be made to show up even if the settings listed aren't set.
