### ISSUE TITLE
Hacktoberfest: Update Dependencies

### ISSUE THREAD

**Issue by klaudiosinani** [klauscfhq/hyper-pokemon#24]
Hello! : )
Celebrating the Hacktoberfest festivities, everyone is welcome to update the project's `dependencies` and `devDependencies` to their latest versions. It should be really simple and easy. Here are the links to the packages on `npmjs.com`, you can find their latest version on the right side of the page:

- [`yaml-lint`](https://www.npmjs.com/package/yaml-lint)
- [`home-dir`](https://www.npmjs.com/package/home-dir)
- [`xo`](https://www.npmjs.com/package/xo)
- [`js-yaml`](https://www.npmjs.com/package/js-yaml)

Happy Hacktoberfest and happy hacking! 🎉

**Comment by nicolaspascual** [comment]
I can go for this

**Comment by klauscfhq** [comment]
@nicolaspascual Definitely  : )
