### ISSUE TITLE
Always shows only pikachu background

### ISSUE THREAD

**Issue by iamstevendao** [klauscfhq/hyper-pokemon#29]
in the `config.pokemon`, I changed it to `random`, `charizard`, `blastoise`, ... full reload the terminal, close and open again but none of them works. It always shows the Pikachu background.  
Any advice?

**Comment by klaudiosinani** [comment]
Could you please share your `~/.hyper.js` configuration?

**Comment by iamstevendao** [comment]
@klauscfhq  This is my config, I had been trying to re-install hyper as well as tried it out on my Windows laptop but both only show the Pikachu background.  
![screenshot_1](https://user-images.githubusercontent.com/15044203/33810098-e8a880d6-de54-11e7-97b0-023d379c1e79.png)

**Comment by klaudiosinani** [comment]
Moving only the 5 theme options directly below the `colors` object should fix the issue : )
Once done, you will be left with something similar to the following;

```js
colors: {
...
},
pokemon: 'gengar', // Define your favorite pokemon theme
pokecursor: 'true', // Activate your theme's pokecursor
pokemonSyntax: 'dark', // Define the color of the terminal tabs
unibody: 'true', // Define the color of the Hyper window header
poketab: 'false', // Deactivate your theme's poketab
```

**Comment by iamstevendao** [comment]
@klauscfhq all good now, but do you think it's a better idea to wrap all your properties inside your theme unique property?  
something similar like this:
```js
colors: 
{
    //...
},
pokemonTheme: {
    pokemon: 'charizard', // Define your favorite pokemon theme
    pokecursor: 'true', // Activate your theme's pokecursor
    pokemonSyntax: 'dark', // Define the color of the terminal tabs
    unibody: 'true', // Define the color of the Hyper window header
    poketab: 'true', // Deactivate your theme's poketab
},
```

It is just my opinion so don't worry if you want to do differently xD.
