### ISSUE TITLE
Gengar font color

### ISSUE THREAD

**Issue by sluongng** [klauscfhq/hyper-pokemon#3]
![image](https://user-images.githubusercontent.com/26684313/27060522-aef04f58-5007-11e7-86e4-b44a7812d732.png)

I am having a really hard time using Gengar theme atm... the color is just all white and sometimes it  goes over the pokemon's teeth thus can see a thing.

**Comment by klaudiosinani** [comment]
It's an issue that it's going to be fixed on the upcoming release, in just a few hours, which will also introduce more new themes 😄 Thanks for dropping by and reporting it!

**Comment by klaudiosinani** [comment]
@sluongng How do you like the updated version?  : )

![hyper_2017-06-13_07-30-55](https://user-images.githubusercontent.com/12670537/27066182-eb106498-500a-11e7-8bf4-039ff7f88dac.png)

**Comment by sluongng** [comment]
Great stuff, cant wait to get home and check it out :+1:

**Comment by georgebax** [comment]
Hey @sluongng, I would also like to point out that zsh with the _Oh My Zsh_  package (http://ohmyz.sh/) is highly recommended to get the most out of our color syntax! (This is what we use in all the screenshots you'll see)

**Comment by sluongng** [comment]
@klauscfhq what color scheme is that? I tried `pokemonSyntax: 'dark,` but that didnt work

**Comment by klaudiosinani** [comment]
@sluongng It will be available in literally minutes, along with a new `unibody` theme option, a new `vulpix` theme & a `readme` instructions update on how to set it up! Stay tuned! 😄

**Comment by klauscfhq** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Gengar Font Color](https://trello.com/c/0VnzRb3F/18-gengar-font-color)
