### ISSUE TITLE
Request: Add theme to Hyper Store

### ISSUE THREAD

**Issue by markusberg-spt** [klauscfhq/hyper-pokemon#34]
## Description

The official Hyper theme store is [now live](https://hyper.is/themes). Would you mind adding it there so more people can access it? 
Original issue thread on the hyper repo is [here](https://github.com/zeit/hyper/issues/2898).
Thank you very much for your work and the theme! 🎉

**Comment by klaudiosinani** [comment]
Theme has been submitted to the store; [#46@hyper-site](https://github.com/zeit/hyper-site/pull/46)
