### ISSUE TITLE
Exclude some pokemon from random

### ISSUE THREAD

**Issue by nasa9084** [klauscfhq/hyper-pokemon#54]
**Is your feature request related to a problem? Please describe.**
Maybe #43 and #12

**Describe the solution you'd like**
I like this pokemon themes, they are very cute, I'm using with `pokemon: 'random'` and hyper-opacity plugin.
However, sometime it is hard to read the text because of its color.
So I want to exclude some pokemons from random, hou about to add `exclude` config option and exclude them?
If it is ok, I will make a PR.

**Additional context**
nothing

**Comment by klaudiosinani** [comment]
Sounds good, PR welcome
