### ISSUE TITLE
Feature Request: Randomize themes by tab

### ISSUE THREAD

**Issue by navarroaxel** [klauscfhq/hyper-pokemon#8]
Hi! your hpm is awesome, and I put here this feature request:

When I select a ``pokemon: 'random'``, or ``pokemon: 'fire'``, or some other pokemon type I want a new theme for every tab I open in Hyper.

Thanks!

**Comment by klaudiosinani** [comment]
Hello! Thank you for taking the time to suggest this feature! 😄 It is definitely on our TODO list and we will try implementing it really soon! In the meantime, for this week's v0.3 release, we plan on adding all Kanto Pokemon themes alongside a significant ammount of Johto Pokemon themes, more `random by type` options and a new `random by region` feature! Feel free to suggest any other feature and stay tuned for the upcoming goodies! 😄

**Comment by bobbystockstead** [comment]
Could this get reprioritized?
